name: whatsapp_chat
description: A new Flutter project.
publish_to: 'none'

version: 1.1.1+11

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  crypto: ^3.0.3
  get: ^4.6.6
  local_auth: ^2.1.7
  flutter_secure_storage: ^9.0.0
  bcrypt: ^1.1.3
  path_provider: ^2.1.4
  http: ^0.13.6
  dio: ^5.1.2
  gal: ^2.3.0
  shared_preferences: ^2.3.2
  mask_text_input_formatter: ^2.9.0
  url_launcher: ^6.3.1
  clipboard: ^2.0.2
  intl: 0.20.2
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_messaging: ^15.2.10
  flutter_native_splash: ^2.2.18
  google_sign_in: ^6.2.1
  firebase_storage: ^12.4.10
  share_plus: ^11.0.0
  animate_do: ^4.2.0
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  video_editor: ^3.0.0
  helpers: ^1.2.3
  pod_player: ^0.2.0
  video_player: ^2.8.7
  permission_handler: ^12.0.1
  record: ^6.0.0
  audio_waveforms: ^1.0.1
  file_picker: ^10.2.0
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  share_handler: ^0.0.17
  timezone: ^0.9.0
  flutter_local_notifications: ^18.0.1
  icon_decoration: ^2.1.0
  video_thumbnail: ^0.5.6
  percent_indicator: ^4.2.3
  firebase_admin: ^0.2.0
  html: ^0.15.4
  google_fonts: ^4.0.3
  emoji_regex: ^0.0.5
  firebase_crashlytics: ^4.3.10
  sign_in_with_apple: ^7.0.1
  url_strategy: ^0.3.0
  fl_chart: ^0.69.0
  timeago: ^3.7.1
  audioplayers: ^5.2.1
  
  # ðŸ“¸ APENAS PROCESSAMENTO DE IMAGENS (SEM FFmpeg)
  image: ^4.1.7  # Para processar imagens
  path: ^1.9.0  # Para manipulaÃ§Ã£o de caminhos

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/img/
    - lib/assets/outros/
    - lib/assets/onboarding/
    - lib/assets/img/logo_leao.png
    - lib/assets/img/disponivelem.png
    - lib/assets/audios/rugido_leao.mp3
    - assets/audios/rugido_leao.mp3